# Generated by Django 5.0.7 on 2024-07-26 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=16)),
                ('count', models.IntegerField()),
                ('sal_from', models.IntegerField()),
                ('sal_to', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_parser.search')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_parser.skill')),
            ],
        ),
    ]
