# Generated by Django 5.0.7 on 2024-07-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='skill_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='world_id',
            field=models.IntegerField(),
        ),
    ]
