# Generated by Django 5.0.7 on 2024-07-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_parser', '0002_alter_requirements_skill_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='skill_id',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='world_id',
            field=models.CharField(max_length=14),
        ),
    ]
